/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_zone_ndktools_NDKTools */

#ifndef _Included_com_android_zone_ndktools_NDKTools
#define _Included_com_android_zone_ndktools_NDKTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_zone_ndktools_NDKTools
 * Method:    getStringFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_zone_ndktools_NDKTools_getStringFromNDK
  (JNIEnv *, jclass);

/*
 * Class:     com_android_zone_ndktools_NDKTools
 * Method:    callbackmethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_zone_ndktools_NDKTools_callbackmethod
  (JNIEnv *, jobject);

/*
 * Class:     com_android_zone_ndktools_NDKTools
 * Method:    callbackIntmethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_zone_ndktools_NDKTools_callbackIntmethod
  (JNIEnv *, jobject);

/*
 * Class:     com_android_zone_ndktools_NDKTools
 * Method:    callbackStringmethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_zone_ndktools_NDKTools_callbackStringmethod
  (JNIEnv *, jobject);

/*
 * Class:     com_android_zone_ndktools_NDKTools
 * Method:    callStaticmethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_zone_ndktools_NDKTools_callStaticmethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
